### ISSUE TITLE
0331 김태완 MSA

### ISSUE THREAD

**Issue by paladyn12** [goorm-sixsens/study#19]
## ▪︎ MSA (Micro Service Architecture)

> 커다란 App을 독립적으로 배포, 운영하는 소프트웨어 개발 방식
> 

할 수 있는 작은 Service 단위로 나누어 개발하는 접근 방식

각 서비스는 고유 기능을 담당하며 다른 서비스와 통신하며 하나의 시스템을 구성

![Image](https://github.com/user-attachments/assets/ce3e024a-a35e-40e6-b082-328a6a8ac06e)
- 장점
    - 확장성, 유지보수 용이성, 독립 배포 가능
    - 서비스가 독립적이기 때문에 Update, Error 발생 시 다른 서비스에 큰 영향 X

# ▫︎  MSA vs Monolithic

> Monolithic Architecture : 모든 기능과 주요 모듈이 하나의 코드베이스
 ⇒ Appliation에 통합된 구조
MSA : 각 기능이 독립된 서비스로 나뉘어져 서로 API 통신
 ⇒ 각 서비스가 독립적인 Apllication 단위

![Image](https://github.com/user-attachments/assets/fcf53a6b-ec5d-4f2f-b280-23cef2965141)
- MSA는 항상 정답인가?
    - MSA는 분산 시스템의 복잡성 증대
     ⇒ 작은 팀이나 프로젝트 초기에는 Monolithic이 효율적
- MSA 도입 시점
    - Application 성장
    - 요구사항 복잡
    - 트래픽 증대와 Application 배포 주기를 줄여야 할 때

## Spring Cloud

> MSA를 구축하고 운영하는데 필요한 다양한 기능을 제공하는 모듈
여러 개별 서비스가 **서로 원활하게 통신하고 관리**될 수 있도록 돕는 도구와 패턴 제공
> 
- Eureka : Netfilx가 개발한 서비스 등록 및 발견 서버
    - 각 서비스는 Eureka 서버에 자신의 정보를 등록
    - 다른 서비스는 이를 통해 필요한 서비스를 찾아 호출
    - Client 측 Load Balancing과 장애 감지 기능 제공
    
# ▫︎  Spring Cloud Architecture

![Image](https://github.com/user-attachments/assets/f46e7357-3251-4e47-971e-1a0b9581bbf4)
- API Gateway
    - Client가 서비스를 요청할 때 접근
    - MSA의 **단일 진입점** (Single Entry Point)
    - API Gateway의 핵심은 **라우팅**, 추가로 **인증, 권한 부여, 로깅** 등 수행
    
![Image](https://github.com/user-attachments/assets/34c99c00-3b33-4641-bdb8-09405540023e)
- Eureka
    - Service Discovery 담당 (각 서비스의 인스턴스 위치를 추적 및 관리)
    - **Eureka Server** : 각 서비스 인스턴스들이 자신의 상태와 위치를 등록하는 중앙 관리 서버
    - **Eureka Client** : 각 서비스는 중앙 서버에 자신을 등록하며 주기적으로 상태를 Health Check
- Load Balancer
    - 서비스 간의 트래픽 분산
    - 각 인스턴스의 상태 (Health Status)를 주기적으로 Check
    - 문제가 있는 Service는 트래픽을 보내지 않음
    - Load Balancer 알고리즘과 스케일 아웃
        - 라운드 로빈 (Round Robin) : 서버에 들어온 요청을 순서대로 돌아가며 처리 (Default)
        - 최소 연결 (Least Connections) : 현재 연결 수가 가장 적은 서버에 새로운 요청을 할당하는 방식
        - 가중 라운드 로빈 (Weighted Round Robin) : 각 서버에 가중치를 부여하고 가중치에 따라 요청 분배
- Instance
    - Client 요청에 따라 주문, 결제, 메뉴 등 각 Port에서 실제 비즈니스 로직을 수행하는 서비스를 제공
- **전체 흐름 정리**
    1. Client의 Request ⇒ API Gateway
    2. API Gateway의 라우팅 ⇒ Eureka Server에 해당 서비스 인스턴스 정보 조회
    3. Load Balancer에게 정보를 전달하여 적절한 Eureka Client 요청 전달
    4. Service Instance는 요청 처리 후 API Gateway를 통해 Client에게 Response
```yaml
// Eureka Server - application.yml

# Eureka Server 8761번 포트
server:
  port: 8761
eureka:
  client:
    # 서버이므로 Client로 등록하지 않음
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
```

```java
// Eureka Server - Application

@SpringBootApplication
/**
 * Spring Cloud Netflix 에서 사용되는 애노테이션
 * 해당 애플리케이션을 Eureka Server로 활성화
 */
@EnableEurekaServer
public class EurekaServerApplication {

    public static void main(String[] args) {
        SpringApplication.run(EurekaServerApplication.class, args);
    }
}
```

```yaml
// Gateway - application.yml

server:
  port:
    #gateway의 포트는 고정
    8000

spring:
  application:
    name: gateway-server
  #API Gateway 서버는 Client 라우팅이 핵심
  cloud:
    gateway:
      routes:
        - id: 1st-service
          uri : lb://1ST-SERVICE # load balancer + Instance Name
          predicates:
            #/first-service 경로로 오는 요청을 1st-service 애플리케이션으로 라우팅
            - Path=/first-service/**
          filters:
            - RewritePath=/first-service/(?<segment>.*), /$\{segment}
        - id: 2nd-service
          uri: lb://2nd-SERVICE
          predicates:
            - Path=/second-service/**
          filters:
            - RewritePath=/second-service/(?<segment>.*), /$\{segment}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
```

```java
// Gateway - Application

@SpringBootApplication
@EnableDiscoveryClient
public class GatewayApplication {

    public static void main(String[] args) {
        SpringApplication.run(GatewayApplication.class, args);
    }
}
```

```yaml
// First Service - application.yml

server:
  # 랜덤 포트
  port: 0

spring:
  application:
    name: 1st-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance-id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
```

```java
// First Service - Application

@SpringBootApplication
@EnableDiscoveryClient
public class FirstServiceApplication {

    public static void main(String[] args) {
        SpringApplication.run(FirstServiceApplication.class, args);
    }
}

// First Service - Controller

@RestController
public class FirstController {

    private final Environment environment;
    public FirstController(Environment environment) {
        this.environment = environment;
    }

    @GetMapping("/health")
    public String health() {
        return "나는 살아있다. 내 포트는 " + environment.getProperty("local.server.port");
    }
}
```

```yaml
// Second Service - application.yml

server:
  # 랜덤 포트
  port: 0

spring:
  application:
    name: 2nd-service

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.instance.instance-id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761//eureka
```

```java
// Second Service - Application

@SpringBootApplication
@EnableDiscoveryClient
public class SecondServiceApplication {

    public static void main(String[] args) {
        SpringApplication.run(SecondServiceApplication.class, args);
    }
}

// Second Service - Controller

@RestController
public class SecondController {

    private final Environment environment;
    public SecondController(Environment environment) {
        this.environment = environment;
    }

    @GetMapping("/health")
    public String health() {
        return "나는 살아있다. 내 포트는 " + environment.getProperty("local.server.port");
    }
}
```

- http://localhost:8761 : Eureka Server
    - Eureka Client로 등록된 애플리케이션들의 상태 확인 가능
- [http://localhost:8000/first-service/health](http://localhost:8000/second-service/health)
- Gateway로 접근
- Eureka Server에 서비스 인스턴스가 있는지 확인하고 Load Balancer에게 정보 전달
- 적절한 Eureka Client(1st Service Application)에게 요청 전달
- 1st Service Application의 포트는 자동 생성되며 해당 애플리케이션의 서비스가 실행 후 API Gateway를 통해 결과를 Client에게 반환
